export const weatherImages = {
  0: 'sun-2699555.svg',
  1: 'sun-2699555.svg',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing rime fog',
  51: 'Drizzle light',
  53: 'Drizzle moderate',
  55: 'Drizzle intensive',
  56: 'Freezing Drizzle (light)',
  57: 'Freezing Drizzle (intensive)',
  61: 'Rain slighty',
  63: 'Rain moderate',
  65: 'Rain heavily',
  66: 'Freezing rain lightly',
  67: 'Freezing rain heavily',
  71: 'Snow fall (slighty)',
  73: 'Snow fall (moderate)',
  75: 'Snow fall (heavily)',
  77: 'Snow grains',
  80: 'Rain showers (slighty)',
  81: 'Rain showers (moderate)',
  82: 'Rain showers (heavily)',
  85: 'Snow showers (slighty)',
  86: 'Snow showers (heavyly)',
  95: 'Thunderstorm',
  96: 'Thunderstorm (slight hail)',
  99: 'Thunderstorm (heavy hail)'
}